"""Renamed users and added teams

Revision ID: 19b46bab068
Revises: 43f122c1fd
Create Date: 2016-02-02 23:14:05.548815

"""

# revision identifiers, used by Alembic.
revision = '19b46bab068'
down_revision = '43f122c1fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=True)
    op.create_table('siteusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_siteusers_email', 'siteusers', ['email'], unique=True)
    op.create_index('ix_siteusers_username', 'siteusers', ['username'], unique=True)
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_siteusers_username', 'siteusers')
    op.drop_index('ix_siteusers_email', 'siteusers')
    op.drop_table('siteusers')
    op.drop_index('ix_teams_name', 'teams')
    op.drop_table('teams')
    ### end Alembic commands ###
