"""Added Teams and Points

Revision ID: 58eb8c49694
Revises: 19b46bab068
Create Date: 2016-02-02 23:35:32.166395

"""

# revision identifiers, used by Alembic.
revision = '58eb8c49694'
down_revision = '19b46bab068'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('header', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_teams_table',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['siteusers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['teams.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_teams_table')
    op.drop_table('points')
    ### end Alembic commands ###
